language: ruby
rvm:
  - 2.7
gemfile:
  - gemfiles/rails5-1
  - gemfiles/rails5-2
  - gemfiles/rails6-0
  - gemfiles/rails6-0-4
  - gemfiles/rails6-1
  - gemfiles/rails7-0
script:
  - bundle exec rake test
