name: Test workflow

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        envs:
          - gemfile: rails5-1
            ruby: '2.7'
          - gemfile: rails5-2
            ruby: '2.7'
          - gemfile: rails6-0
            ruby: '2.7'
          - gemfile: rails6-1
            ruby: '2.7'
          - gemfile: rails7-0
            ruby: '2.7'
          - gemfile: rails7-1
            ruby: '2.7'
          - gemfile: rails7-2
            ruby: '3.1'

    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.envs.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.envs.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
